#!/bin/bash

#update system
echo "Updating system..."
echo " "
	apt update -qq
	apt upgrade -y
	apt autoremove -y
	apt autopurge -y
	apt autoclean -y

echo " "
echo " "
echo " "
echo "System up-to-date!"
echo " "
echo " "
echo " "

#apt
echo " "
echo " "
echo " "
echo "Installing useful tools and features..."
echo " "
echo " "
echo " "

	apt install vlc-bin -y
	apt install tree -y
	apt install ssh -y
	apt install git -y
	apt install gamemode -y

echo " "
echo " "
echo " "
echo "Useful features and tools installed!"
echo " "
echo " "
echo " "

#apt uninstaller
echo " "
echo " "
echo " "
echo "Uninstalling useless libs..."
echo " "
echo " "
echo " "

	apt remove gnome-online-accounts-gtk -y
	apt remove warpinator -y
	apt remove thunderbird -y
	apt remove rhythmbox -y
	apt remove hypnotix -y
	apt remove thunar-data -y
	apt remove mintchat -y
	apt remove sticky -y
	apt remove transmission-gtk -y
	apt remove pix -y
	apt remove pix-dbg -y

echo " "
echo " "
echo " "
echo "Useless libs removed!"
echo " "
echo " "
echo " "

#Flatpak
echo " "
echo " "
echo " "
echo "Installing essentials and helpful flatpaks..."
echo " "
echo "Choose always the STABLE and LATEST version!"
echo "For example: For Wine, choose 7."
echo " "
echo " "
echo " "
	flatpak install org.winehq.Wine
echo ""
echo "For kde.Platform, choose 1.(Or latest)"
echo ""
	flatpak install org.kde.Platform
echo ""
echo "For gnome.PLatform, choose 19. (Or latest)"
echo ""
	flatpak install org.gnome.Platform
echo ""
echo "If Flatseal asks for version, choose the latest one."
echo ""
	flatpak install com.github.tchx84.Flatseal

echo " "
echo " "
echo " "
echo "Flatpaks installed!"
echo " "
echo " "
echo " "
echo "Everything done!"
echo "Enjoy! :D"
echo " "
