#!/bin/bash

# =============================================

# Script: screen (lock | off | on) (null | all)

# =============================================

case "$1" in
    lock)
	# Lock all screens
        cinnamon-screensaver-command --lock
        echo
	echo "Screen locked."
	echo
        ;;

    off)
    # Turn off ALL monitors.
    if [ "$2" = "all" ]; then
		export DISPLAY=:0; xrandr --output eDP-1 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output HDMI-1 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-1 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-2 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-3 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output HDMI-2 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output VGA-1 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output LVDS-1 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-1-1 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-1-2 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output HDMI-A-1 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output HDMI-D-1 --off 2>/dev/null
		echo
		echo "All monitors turned off."
		echo
    else
        # Turn off the main monitor.
	type=$(inxi -M | grep "Type:" | awk -F': ' '{print $2}' | awk '{print $1}')
        if [ "$type" = "Laptop" ]; then
		export DISPLAY=:0; xrandr --output eDP-1 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-1 --off 2>/dev/null
		echo
        	echo "Main screen turned off."
		echo
	else
		export DISPLAY=:0; xrandr --output HDMI-1 --off 2>/dev/null
		export DISPLAY=:0; xrandr --output VGA-1 --off 2>/dev/null
		echo
		echo "Main screen turned off."
		echo
		fi
	fi
	;;

    on)
    # Turns on ALL monitors.
	if [ "$2" = "all" ]; then
		export DISPLAY=:0; xrandr --output eDP-1 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output HDMI-1 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-1 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-2 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-3 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output HDMI-2 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output VGA-1 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output LVDS-1 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-1-1 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output DP-1-2 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output HDMI-A-1 --auto 2>/dev/null
		export DISPLAY=:0; xrandr --output HDMI-D-1 --auto 2>/dev/null
		echo
        	echo "All monitors turned on."
		echo
    else
    	# Turn on the main monitor.
	type=$(inxi -M | grep "Type:" | awk -F': ' '{print $2}' | awk '{print $1}')
        if [ "$type" = "Laptop" ]; then
		        export DISPLAY=:0; xrandr --output eDP-1 --auto 2>/dev/null
                export DISPLAY=:0; xrandr --output DP-1 --auto 2>/dev/null
		    echo
        	echo "Main screen turned on."
		    echo
	    else
		        export DISPLAY=:0; xrandr --output HDMI-1 --auto 2>/dev/null
                export DISPLAY=:0; xrandr --output VGA-1 --auto 2>/dev/null
                echo
                echo "Main screen turned on."
                echo 
		fi
	fi
    ;;

    help|-h|--help)
echo ""
echo ""
        echo " Commands:"
        echo " Use: screen {option} {all} or null"
	echo " Ex1.: screen off"
	echo "	Just turn off the main monitor where terminal is running."
echo ""
	echo " Ex2.: screen {on/off} all"
	echo "	Turn on/off ALL of your monitors."
echo ""
echo ""
echo ""

        echo "   screen lock             -> Locks your screen"
        echo "   screen off              -> Turns off your monitor"
        echo "   screen on               -> Turns on your monitor"
        echo "   screen {option} all     -> Perform action to ALL monitors. "
echo ""
	echo " !! Lock option runs at all monitors as default."
echo ""
        ;;

	*)
echo ""
	echo " Wrong command!"
	echo " Run 'screen help' for help"
echo ""
	;;

esac
