#!/bin/bash

clear

sudo echo

DISTRO=$(grep "^ID=" /etc/os-release | cut -d'=' -f2)

echo
echo " UP-date SYS-tem "
echo " By DESU "
echo 
echo "Visit: https://github.com/desu-is-afk for more projects"
echo 
echo " Press Ctrl + C to cancel "
echo " Starting UPSYS in three seconds... "
echo

sleep 4

# RHEL | RHEL | RHEL | RHEL | RHEL | RHEL | RHEL | RHEL | RHEL | RHEL | RHEL | RHEL | RHEL | RHEL

case "$DISTRO" in
    fedora|rhel|centos|rocky|almalinux)

        echo "Detected: Red_Hat-Based (RHEL)"
        echo
        echo " !! Updating system..."
        echo

        sudo dnf up

        clear
        echo
        echo " !! Running automatic cleaner..."
        echo
        
        sudo dnf autoremove	
        clear
        
        echo  
        echo " System full updated"
        echo
            ;;

# DEBIAN | DEBIAN | DEBIAN | DEBIAN | DEBIAN | DEBIAN | DEBIAN | DEBIAN | DEBIAN | DEBIAN | DEBIAN

    ubuntu|linuxmint|pop|debian|kali)

        echo "Detected: Debian-Based"
        echo
        echo " !! Updating system..."
        echo
        
        sudo apt update -qq
        clear

        echo
        echo " !! Upgrading system..."
        echo

        sudo apt upgrade -y
        clear

        echo
        echo " !! Running automatic cleaner..."
        echo

        sudo apt autoremove -y
        sudo apt autoclean -y
        sudo apt autopurge -y

        clear
        echo
        echo " !! Updating Flatpaks..."
        echo

        flatpak update -y
        
        clear
        echo  
        echo " System full updated"
        echo

        ;;

# ARCH | ARCH | ARCH | ARCH | ARCH | ARCH | ARCH | ARCH | ARCH | ARCH | ARCH | ARCH | ARCH | ARCH

    arch|manjaro|endeavouros|garuda|cachyos)
        
        echo "Detected: Arch-Based"
        echo
        echo " Updating system..."

        sudo pacman -Syu --noconfirm
        clear

        echo
        echo " !! Running automatic cleaner..."
        echo

        sudo pacman -Rns $(pacman -Qdtq) --noconfirm
        clear

        echo
        echo " !! Cleaning down-dated cache..."
        echo

        sudo pacman -Scc
        clear
        ;;
# ERROR | ERROR | ERROR | ERROR | ERROR | ERROR | ERROR | ERROR | ERROR | ERROR | ERROR | ERROR 
    
    *)
        echo " !!"
        echo "Error: Distribuição não reconhecida: $DISTRO"
        echo " !!"
        ;;
esac
# exit
